defaults:
  - defaults
  - task_factory: simple_grasp_task
  - oracle: simple_grasp_oracle
  - camera_factory: static
  - _self_

debug: false
render: false
store_dataset: true
dataset_directory: ${data_root}/datasets/tn_train_data

n_scenes: 10